// Package domain defines the entities of llm-ms.
// llm-ms has no banking logic of its own — it only mirrors transactions
// (materialized view) and stores explanations generated by the LLM.
package domain

import (
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

var (
	ErrTransactionNotFound = errors.New("transaction not found in view")
	ErrExplanationNotFound = errors.New("explanation not found")
)

// TransactionView is the local copy llm-ms keeps of transactions,
// fed by Kafka events.
type TransactionView struct {
	ID            uuid.UUID
	Type          string
	Status        string
	FromAccountID *uuid.UUID
	ToAccountID   *uuid.UUID
	Amount        decimal.Decimal
	Currency      string
	RejectionCode string
	RejectionMsg  string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// Explanation is the text generated by Claude (or the mock) for a tx.
type Explanation struct {
	TxID        uuid.UUID
	Text        string
	Model       string
	GeneratedAt time.Time
}

// ChatMessage is one message in the chat array (user or assistant).
// The front keeps the history and sends it on every request.
type ChatMessage struct {
	Role    string `json:"role"    validate:"required,oneof=user assistant"`
	Content string `json:"content" validate:"required,min=1"`
}
